### ISSUE TITLE
pandoc on windows to old?

### ISSUE THREAD

**Issue by ThierryO** [r-universe-org/help#119]
Inspecting the raw log of [this failed run](https://github.com/r-universe/inbo/runs/4869573927?check_suite_focus=true) on Windows (R-release and R-old-rel) I found the message below.

`##[error]Error: callr subprocess failed: pandoc version 1.12.3 or higher is required and was not found (see the help page ?rmarkdown::pandoc_available).`

**Comment by ThierryO** [comment]
I'm still having this issue. See https://github.com/r-universe/inbo/actions/runs/3053299242

How can I make sure to install the required pandoc version?

**Comment by ThierryO** [comment]
Would adding `SystemRequirements: Pandoc (>= 1.17.2)` to the `DESCRIPTION` ensure that a sufficient version of pandoc is installed under Windows?

**Comment by remlapmot** [comment]
I am also having this problem.

This is with my co-authored package Statamarkdown included in my personal r-universe <https://remlapmot.r-universe.dev/Statamarkdown>.

It may also be because we have forgotten to include pandoc in the DESCRIPTION.

For my package only the Windows builds fail; whereas the macOS, Linux, and webassembly builds all pass.

The failing Windows builds are shown here <https://github.com/r-universe/remlapmot/actions/runs/8128016826>.

**Comment by remlapmot** [comment]
@jeroen would you have any insight into these failed jobs on Windows? It's a bit frustrating that they only fail on Windows and this package does build on CRAN without the pandoc min version in SystemRequirements.

**Comment by jeroen** [comment]
Thanks, I have now added pandoc to the standard Windows environment. Let me know if you run into any further problems.

**Comment by remlapmot** [comment]
Super - thanks so much
