### ISSUE TITLE
Registry fails to update with 'unpacking the sent packfile failed on the remote'

### ISSUE THREAD

**Issue by Bisaloo** [r-universe-org/help#152]
https://github.com/r-universe/epiforecasts/actions/workflows/sync.yml

> ERROR updating forecast.vocs from https://github.com/epiforecasts/forecast.vocs (unpacking the sent packfile failed on the remote)
> 
> 
> ERROR updating socialmixr from https://github.com/epiforecasts/socialmixr (unpacking the sent packfile failed on the remote)
> 
> 
> ERROR updating cmdstanr from https://github.com/stan-dev/cmdstanr (unpacking the sent packfile failed on the remote)
> 
> Error in sync::sync_from_registry("https://github.com/r-universe/epiforecasts") : 
>   Failed to update packages: forecast.vocs, socialmixr, cmdstanr

**Comment by jeroen** [comment]
I thought maybe the repo is corrupted somehow, so I deleted it and started from scratch, but the problem persists...

**Comment by jeroen** [comment]
OK I found the problem. The root cause is a syntax error in the `Authors@R` field from the description file in forecast.vocs.

Your last commit of the description file added an author, however you have mixed up the parenthesis and therefore instead of two `person()` objects, you have one `person()` which is nested into another. Somehow R accepts this and we get a malformed maintainer signature.

I have added a step to the universe sync function that tries to validate the maintainer sig before using it in the commit: https://github.com/r-universe-org/sync/commit/42e61e5d75dbd7d10c0f9960b0f5e243f9fe56b4

**Comment by Bisaloo** [comment]
Ah yes, good catch. And socialmixr had a similar issue that I fixed a couple of days ago: https://github.com/epiforecasts/socialmixr/commit/541d1706b8692035db5bd24ee9830a9b92b4ff52 (missing closing parenthesis on L13).

Thanks for your help!
