### ISSUE TITLE
Update submodules: fails with `HTTP error 404` during `Sync Registry` step

### ISSUE THREAD

**Issue by mrustl** [r-universe-org/help#169]
Hi @jeroen, 

any idea why this is happening in our [KWB-R universe](https://github.com/r-universe/kwb-r/)?:

`ERROR updating pkgmeta from https://github.com/KWB-R/pkgmeta (HTTP error 404.)`

https://github.com/r-universe/kwb-r/runs/6696970052?check_suite_focus=true#step:3:131

**Comment by jeroen** [comment]
It is unable to find the DESCRIPTION file in one of your remotes: https://raw.githubusercontent.com/UptakeOpenSource/pkgnet/HEAD/DESCRIPTION

**Comment by jeroen** [comment]
I think the problem is that the packages lives in a subdir of the remote git repo, which is not specified.

Yeah the output is a bit unclear, because the error gets postponed to the end until all packages are processed. But if you scroll up a git in the log you can see the urls that it is trying to download, so that is where the error happend. I'll try to make that more clear

**Comment by mrustl** [comment]
Very cool! And thanks for your fast response! 

well interestingly installing from GitHu using `remotes` is working for both:
```
remotes::install_github("UptakeOpenSource/pkgnet@d1e974de299d46e71b082e027a71b8b254edc9b2")
remotes::install_github("uptake/pkgnet@d1e974de299d46e71b082e027a71b8b254edc9b2")
```

Maybe the `redirect` from https://github.com/UptakeOpenSource/pkgnet to github.com/uptake/pkgnet is not handled by r-universe?

**Comment by jeroen** [comment]
Looks like your registry has been fixed!

**Comment by mrustl** [comment]
Yeah working again. Maybe this is something for the FAQ as the behavior of `raw github api` and `remotes::install_github()` differs, so there is no way to find beforehand using GH CI that there is an renaming issue with the dependency!
