### ISSUE TITLE
Link to specific sections of package pages

### ISSUE THREAD

**Issue by maelle** [r-universe-org/help#178]
For instance I'd like to be able to link directly to "development and contributors".
What's needed is an header id ("easy"), potentially something like headings on rOpenSci blog (the anchor icon, less easy)

**Comment by jeroen** [comment]
I'd like this too but it requires a bit rewrite of the front-end, because currently every package page is it's own anchor, for example: `https://ropensci.r-universe.dev/ui#package:magick` already uses `#package:magick` to navigate to the package page.

So we would need to rewrite things such that each package gets a full url I think. Which would be better anyway but it's quite a bit of work.

**Comment by maelle** [comment]
Thank you!! A anchor icon on hover or something similar would be nice, as otherwise one does not know there's the ID?

**Comment by maelle** [comment]
I think this can be closed, thanks a ton for the new feature :sparkles: :star2:
