### ISSUE TITLE
r-universe disabled when github username changes

### ISSUE THREAD

**Issue by drmowinckels** [r-universe-org/help#203]
This summer I changed my github username and as a result my universe got disabled. Its easy enough to get back up, and might not be any other way to get about iit, but thought i'd just point it out, incase it was unknown/unwanted behaviour.

**Comment by jeroen** [comment]
Didn't it automatically set up your new universe under your new username? I would expect it would automatically delete the old one and then create the new one.

R-universe can't see that your username changed, so the old and the new users are just treated like 2 different users. So I would expect it would first delete the old one when it no longer exists, and then (maybe after a day) detect there is a new user and set that one up.

**Comment by drmowinckels** [comment]
it didnt. For some reason, I had to re-add the connection to r-universe. None of my other integrations needed that.

**Comment by jeroen** [comment]
The dashboard shows all packages that are maintained by you. The duplicates show because you added the same package in two different universes for example ggseg is in:

 - https://github.com/drmowinckels/universe/blob/HEAD/packages.json
 - https://github.com/ggset/universe/blob/HEAD/packages.json

You can probably remove packages from your personal registry that are already listed in r-universe/ggseg as well.

**Comment by drmowinckels** [comment]
I see. The reduction helped for sure. THough, some of them were not listed in my personal json either, but might have been left over from before? I have duplication still, but that is because the three main ggseg packages are also listed in the lifebrain universe, as its a key source for package from that EU project and I need to make the project output as visible as possible.

**Comment by drmowinckels** [comment]
ok. thanks for the help @jeroen . It all seems tidy now.
