### ISSUE TITLE
Rebuild `lme4` on R-oldrel Windows runners for Matrix ABI issue

### ISSUE THREAD

**Issue by andrjohns** [r-universe-org/help#426]
Would it be possible to trigger a rebuild of the `lme4` package used in the `windows-oldrel` builders? (currently `https://p3m.dev/cran/latest/bin/windows/contrib/4.3/lme4_1.1-35.3.zip`)

It looks like there's a mismatch with the `Matrix` version, causing runtime errors:

https://github.com/r-universe/stan-dev/actions/runs/9400980424/job/25893445796#step:5:1064

Thanks!

**Comment by glin** [comment]
Thanks for the heads up. We had already rebuilt `lme4` for R 4.4, but apparently the `Matrix` issue affects R 4.3 as well.

Sadly there's no way to provide an `lme4` binary for R 4.3 that's compatible with all versions of R 4.3.x. R 4.3.2 and below come with a `Matrix` with ABI version 0, and R 4.3.3 comes with `Matrix` 1.6-5 with ABI version 1. CRAN no longer provides a newer version of Matrix that's installable on R <= 4.3, so you're stuck with the default versions without other workarounds.

We will possibly remove the `lme4` binaries for R 4.3 to force source installation, since it's no longer possible to provide those binaries without breaking someone's R 4.3.x installation. As a workaround, could you force Matrix to install from source instead of binary?

**Comment by jeroen** [comment]
Thanks for the clarification. Afaict, the binary has been updated, because we get a different error now :) Not sure if this is again an Matrix/lme4 compat problem or something else. But either way this is not something that we can fix in r-universe. Perhaps just disable the test for R <= 4.3?

**Comment by glin** [comment]
We have rebuilt lme4 and all Matrix dependent packages to be compatible with R 4.3.3, rather than R 4.3.2 and below. This was a compromise assuming R 4.3 users would more likely be on 4.3.3 than an older patch version. R <= 4.3.2 users can still upgrade to 4.3.3 or manually install a newer Matrix version.

Can you try rerunning the test now?
