### ISSUE TITLE
Inaccurate "duplicate" banner on r-universe repo page

### ISSUE THREAD

**Issue by francisbarton** [r-universe-org/help#537]
Hi

If I visit https://cynkra.r-universe.dev/tv there is a banner at the top saying "This package is considered a duplicate."

![image](https://github.com/user-attachments/assets/1df8c9ab-1aa5-4176-8bc5-fdbc51b40b5e)

However the repository linked to in the banner (https://eheinzen.r-universe.dev/tv) is not the same package at all. Something wrong with the logic used to trigger the banner message?

**Comment by jeroen** [comment]
I think it is working as intended. Both packages have the same name, and we treat the one that is on CRAN as the official version. We warn users against this because R will automatically overwrite one package with the other when running install.packages or update.packages. This becomes a total mess when other packages `import(tv)`. 

  So `cynkra` probably will have to rename their package, or try to convince the other maintainer to remove their `tv` from CRAN.
