### ISSUE TITLE
Implement download metrics

### ISSUE THREAD

**Issue by Bisaloo** [r-universe-org/help#89]
It would be useful to have some download metrics for package. It would be another advantage of using r-universe vs remotes for the development version of packages.

(I was not sure whether feature requests should be posted here or in the 'Discussions' space. Please feel free to move this if necessary.)

**Comment by kadyb** [comment]
It would be great if it would be possible to get statistics about package downloads as easily as from the RStudio CRAN mirror using the {cranlogs} package.

**Comment by jeroen** [comment]
Thanks for the suggestion :-) 

Just a little explanation what makes it difficult: I am afraid that the metrics will be off, because the majority of downloads may be from other CI runs of r-universe, rather than actual users. So this will inflate the statistics, especially for universes with many packages where a run of pkg A downloads pkg B and so on (this is btw why CRAN downloads statistics are highly inflated as well).

Another issue is that popular files may get served via our CDN cache (cloudflare) so the request may not reach the back-end server, making it difficult to count them.

All in all I was worried that raw back-end downloads would be too inaccurate to expose them.

**Comment by Bisaloo** [comment]
Thanks for the detailed answer!

To clarify, do you see this as "this is a list of things explaining why I want to take it slow and make sure I reduce all possible sources of inaccuracy" or "this is a list of reasons why I'm not likely to do it"?

**Comment by jeroen** [comment]
The first. I do think having some sort of download stats is useful, but perhaps try to improve them a little bit first...

**Comment by maelle** [comment]
A bit off topic, regarding CRAN download stats: https://blog.r-hub.io/2020/05/11/packagerank-intro/

**Comment by sebffischer** [comment]
Would it be possible to specify whether a packages is used for a CI run when downloading a package from r-universe? 

Also I think that even having raw downloads is useful as you can still detect trends to determine whether your user-base is growing or not.

**Comment by jeroen** [comment]
Moving to: https://github.com/r-universe-org/help/issues/528
